[theme]
primaryColor = "#1f4e79"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableCORS = false
# Last updated: lunes,  1 de diciembre de 2025, 09:39:56 -03
